### ISSUE TITLE
8.1.3 字符串加密算法怎么加进去？跑demo没有效果

### ISSUE THREAD

**Issue by asomeLiao** [AloneMonkey/iOSREBook#13]
还想请教下修改 CXToken 内容 如何保存到文件。

**Comment by AloneMonkey** [comment]
直接写到文件对应位置

**Comment by Otrshen** [comment]
请问339页的加解密代码怎么用？不是很理解。 @AloneMonkey

**Comment by Otrshen** [comment]
请问这里的加密你跑通了吗？ @asameLiao

**Comment by asomeLiao** [comment]
加密的算法 加到showstring 就好了

**Comment by Otrshen** [comment]
你加下我QQ吧，我感觉加这里好像不对啊。QQ:569818710 @asameLiao

**Comment by asomeLiao** [comment]
@LarkNan 需要验证问题，过来条件你可以在 函数 printVisitor 中自己定义

**Comment by Otrshen** [comment]
嗯嗯，我后来想通了。就是把静态字符串替换成一个解密方法就可以了吧。
