### ISSUE TITLE
对于书中3.2.2 class-dump 原理一章低36页协议解析一处疑问。

### ISSUE THREAD

**Issue by blackchena** [AloneMonkey/iOSREBook#2]
Data LO 和 Data HI 如何转换为虚拟地址呢？

**Comment by blackchena** [comment]
该节中39页class_rw_t *data()方法，为什么能突然从上文中可以定位到该方法，该方法和value & ~7 怎么扯上关系的呢？

**Comment by AloneMonkey** [comment]
定位的部分没有细讲，运行之后Xcode会定位到crash的代码行，那里有个assert失败，然后追溯这个值的生成可以定位到objc2Class.data读取数据的问题。
