### ISSUE TITLE
WhatsApp的动态调试  Xcode的脚本运行文件你能给一下吗

### ISSUE THREAD

**Issue by xhzth7091** [AloneMonkey/iOSREBook#26]

**Comment by AloneMonkey** [comment]
你说的是这个？ https://github.com/AloneMonkey/iOSREBook/tree/master/chapter-7/7.2%20%E9%9D%9E%E8%B6%8A%E7%8B%B1%E9%80%86%E5%90%91/WhatsApp

**Comment by AloneMonkey** [comment]
还是这个？ https://github.com/AloneMonkey/iOSREBook/blob/master/chapter-5/5.2%20%E5%8A%A8%E6%80%81%E8%B0%83%E8%AF%95/Snapchat/pack.sh

**Comment by xhzth7091** [comment]
你动态调试‎WhatsApp的脚本。
![Xnip2019-05-07_09-33-47](https://user-images.githubusercontent.com/13980546/57265775-c8acd800-70ab-11e9-8565-9c61c5444490.jpg)

**Comment by AloneMonkey** [comment]
视频？  课程里面有附件下载。
