### ISSUE TITLE
越狱

### ISSUE THREAD

**Issue by yeyifeng1991** [AloneMonkey/iOSREBook#3]
请问ios11.3-11.4怎么越狱,书中只介绍了10.0系统的越狱

**Comment by AloneMonkey** [comment]
手里没11的设备，没有试过11.3-11.4的越狱，不好给出意见

**Comment by Vxer-Lee** [comment]
Coolstar Electra

**Comment by Vxer-Lee** [comment]
iOS11~11.3.1
https://media.weibo.cn/article?id=2309404259547190559002&from=singlemessage&isappinstalled=0

iOS 11.4 beta 1,2,3
https://media.weibo.cn/article?id=2309404260242023174545&from=singlemessage&isappinstalled=0

这里感谢 CoolStar为 越狱社区做出的贡献 !!!!!

**Comment by xcuYao** [comment]
各个版本iOS的越狱方案
https://canijailbreak.com/
