### ISSUE TITLE
书中365页编译生成Xcode项目时遇到问题。

### ISSUE THREAD

**Issue by aquarius1212** [AloneMonkey/iOSREBook#4]
执行了这局cmake -G Xcode CMAKE_BUILD_TYPE="Debug" ../llvm

报错如下：
CMake Error at /usr/local/Cellar/cmake/3.12.0/share/cmake/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/a1/Desktop/ollvm/build/CMakeFiles/CMakeTmp
    
    Run Build Command:"/usr/bin/xcodebuild" "-project" "CMAKE_TRY_COMPILE.xcodeproj" "build" "-target" "cmTC_56fce" "-configuration" "Debug"
    Build settings from command line:
        TOOLCHAINS = com.apple.dt.toolchain.XcodeDefault
    
    === BUILD TARGET cmTC_56fce OF PROJECT CMAKE_TRY_COMPILE WITH CONFIGURATION Debug ===
    
    Check dependencies
    target specifies product type 'com.apple.product-type.tool', but there's no such product type for the 'iphonesimulator' platform
    
    ** BUILD FAILED **
    
    
    The following build commands failed:
    	Check dependencies
    (1 failure)

**Comment by AloneMonkey** [comment]
cmake -G "Xcode"  try try

**Comment by aquarius1212** [comment]
还是不行，-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -- broken
CMake Error at /usr/local/Cellar/cmake/3.12.0/share/cmake/Modules/CMakeTestCCompiler.cmake:52 (message):
我根据这个信息定位到CMakeTestCCompiler.cmake文件
if(CMAKE_C_COMPILER_FORCED)
  # The compiler configuration was forced by the user.
  # Assume the user has configured all compiler information.
  set(CMAKE_C_COMPILER_WORKS TRUE)
  return()
endif()
这一句应该是没有执行，导致CMAKE_C_COMPILER_WORKS这个变量的值是FALSE，所以判定xcode自带的clang是broken的，我的xcode版本是9.4，庆哥是因为我xcode版本的问题么？

**Comment by AloneMonkey** [comment]
没关系的，我几个版本的可以cmake

**Comment by aquarius1212** [comment]
Change Dir: /Users/a1/Desktop/ollvm/build/CMakeFiles/CMakeTmp
    
    Run Build Command:"/usr/bin/xcodebuild" "-project" "CMAKE_TRY_COMPILE.xcodeproj" "build" "-target" "cmTC_d44cc" "-configuration" "Debug"
    Build settings from command line:
        TOOLCHAINS = com.apple.dt.toolchain.XcodeDefault
    
    === BUILD TARGET cmTC_d44cc OF PROJECT CMAKE_TRY_COMPILE WITH CONFIGURATION Debug ===
    
    Check dependencies
    target specifies product type 'com.apple.product-type.tool', but there's no such product type for the 'iphonesimulator' platform
    我觉得可能是这个product type 配置出的问题，因为我按照您《关于LLVM，这些东西你必须知道！》这篇文章的的步骤
mkdir build
cmake /path/to/llvm/source
cmake --build .
执行的时候报错是这样的
[  1%] Building AttributesCompatFunc.inc...
dyld: mach-o, but built for simulator (not macOS)
/bin/sh: line 1: 50317 Abort trap: 6           ../../bin/llvm-tblgen -gen-attrs -I /Users/a1/Desktop/ollvm/llvm/lib/IR -I /Users/a1/Desktop/ollvm/llvm/include /Users/a1/Desktop/ollvm/llvm/lib/IR/AttributesCompatFunc.td -o /Users/a1/Desktop/ollvm/build/lib/IR/AttributesCompatFunc.inc.tmp
make[2]: *** [lib/IR/AttributesCompatFunc.inc.tmp] Error 134
make[1]: *** [lib/IR/CMakeFiles/AttributeCompatFuncTableGen.dir/all] Error 2
make: *** [all] Error 2
想请问一下这个simulator配置是在哪里可以改掉呢？

**Comment by AloneMonkey** [comment]
这个我也不知道，之前没有遇到过。

**Comment by aquarius1212** [comment]
嗯，庆总，可以进你的微信群么，之前的入群二维码失效了。这个问题我也请教了下张总，他说正常别人想弄成这样都没办法，应该是以前哪里误操作alias了clang之类的，我换了一台电脑就可以了。

**Comment by AloneMonkey** [comment]
https://github.com/AloneMonkey/MonkeyDev
readme有加入方式。

**Comment by quietStefan** [comment]
庆总，readme的进群方式移除了吗？
