### ISSUE TITLE
你好 8.1.3字符串加密那里 LibClangParse是要怎么用到自己的项目中?

### ISSUE THREAD

**Issue by zhujieshan** [AloneMonkey/iOSREBook#5]

**Comment by AloneMonkey** [comment]
1. 自己遍历源文件处理
2. 干预到clang的流程里面去处理

可以自己发挥一下

**Comment by zhujieshan** [comment]
void *hand = dlopen("/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib",RTLD_LAZY); 
hand的值为空 是我有什么没配置吗

**Comment by AloneMonkey** [comment]
![image](https://user-images.githubusercontent.com/5118864/43249610-b4b473f6-90ed-11e8-8e2d-61c12eeaae45.png)

文件在吗？

**Comment by zhujieshan** [comment]
恩恩 可以了 我的错...
