### ISSUE TITLE
章节5.3.2中需要说明一下

### ISSUE THREAD

**Issue by mgfjx** [AloneMonkey/iOSREBook#6]
新建的app`bundleId`要和目标app保持一致，否则无法安装。
我在脚本签名前加了这段代码，貌似可行：
`/usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier $PRODUCT_BUNDLE_IDENTIFIER" $TARGET_APP_PATH/info.plist`

**Comment by AloneMonkey** [comment]
https://github.com/AloneMonkey/MonkeyDev/blob/master/Tools/pack.sh#L176
