### ISSUE TITLE
5.3.1 Theos 中的一条命令存在笔误

### ISSUE THREAD

**Issue by NinthKnight** [AloneMonkey/iOSREBook#7]
168页 5.3.1 Theos的安装这一节中，“然后，从GitHub上拉取Theos代码.....“这一段的下面命令存在一个无伤大雅的笔误，
原文是
sudo clone --recursive https//github.com/theos/theos.git /opt/theos
在clone前漏掉了git，应为：
sudo git clone --recursive https//github.com/theos/theos.git /opt/theos

**Comment by AloneMonkey** [comment]
感谢指出! 已加到勘误！
