### ISSUE TITLE
在生成bitcode时候无法找到头文件

### ISSUE THREAD

**Issue by aquarius1212** [AloneMonkey/iOSREBook#8]
1deMacBook-Pro:~ Banson$ /Users/a1/Desktop/ollvm/build/Debug/bin/clang -emit-llvm -c /Users/a1/Desktop/main.mm -o /Users/a1/Desktop/main.bc
/Users/a1/Desktop/main.mm:10:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
1 error generated.
1deMacBook-Pro:~ Banson$ /Users/a1/Desktop/ollvm/build/Debug/bin/clang -emit-llvm -c /Users/a1/Desktop/test/test/test.mm -o /Users/a1/Desktop/test.bc
/Users/a1/Desktop/test/test/test.mm:10:9: fatal error: 
      'Foundation/Foundation.h' file not found
#import <Foundation/Foundation.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

**Comment by AloneMonkey** [comment]
main.mm 里面的内容是什么？   Foundation 需要使用 Apple 的 SDK。

**Comment by aquarius1212** [comment]
main.mm里面内容和书中的test内容相同，是一个简单的加法函数。

**Comment by AloneMonkey** [comment]
`xcode-select --install` 试试

**Comment by aquarius1212** [comment]
完美解决，庆总V5
